###

_PLAYER_NAME = "FPM"

_SOCKET_WHITE_PLAYER_PORT = 5800
_SOCKET_BLACK_PLAYER_PORT = 5801

_PLAYER_ROLE_BLACK_ID = "black"
_PLAYER_ROLE_WHITE_ID = "white"

###

APP_DEBUG = True
APP_HOST = '127.0.0.1'
APP_PORT = None
APP_ROLE = None

SERVER_HOST = '127.0.0.1'
SERVER_PORT = None
SERVER_ROLE = None

GAME_MOVE_TIMEOUT = 60.0
